server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    druid:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # 生产环境关闭SQL日志
    log-impl:

reggie:
  path: ${UPLOAD_PATH:./uploads}
