server:
  port: 8080

spring:
  application:
    name: reggie_take_out
  profiles:
    active: dev  # 默认开发环境

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 项目配置
reggie:
  path: ./uploads
