const areaPage = (params) => $axios({ url: '/api/dining/area/page', method: 'get', params })
const areaList = () => $axios({ url: '/api/dining/area/list', method: 'get' })
const addArea = (params) => $axios({ url: '/api/dining/area', method: 'post', data: params })
const updateArea = (params) => $axios({ url: '/api/dining/area', method: 'put', data: params })
const deleteArea = (id) => $axios({ url: `/api/dining/area/${id}`, method: 'delete' })
const getArea = (id) => $axios({ url: `/api/dining/area/${id}`, method: 'get' })

const tablePage = (params) => $axios({ url: '/api/dining/table/page', method: 'get', params })
const addTable = (params) => $axios({ url: '/api/dining/table', method: 'post', data: params })
const updateTable = (params) => $axios({ url: '/api/dining/table', method: 'put', data: params })
const deleteTable = (id) => $axios({ url: `/api/dining/table/${id}`, method: 'delete' })
const getTable = (id) => $axios({ url: `/api/dining/table/${id}`, method: 'get' })
const updateTableStatus = (params) => $axios({ url: '/api/dining/table/status', method: 'put', data: params })
const tableQrcode = (id) => $axios({ url: `/api/dining/table/qrcode/${id}`, method: 'get' })

const queuePage = (params) => $axios({ url: '/api/dining/queue/page', method: 'get', params })
const queueTake = (params) => $axios({ url: '/api/dining/queue/take', method: 'post', data: params })
const queueCall = () => $axios({ url: '/api/dining/queue/call', method: 'put' })
const queueCancel = (id) => $axios({ url: `/api/dining/queue/cancel/${id}`, method: 'put' })

const reservationPage = (params) => $axios({ url: '/api/dining/reservation/page', method: 'get', params })
const addReservation = (params) => $axios({ url: '/api/dining/reservation', method: 'post', data: params })
const confirmReservation = (id) => $axios({ url: `/api/dining/reservation/confirm/${id}`, method: 'put' })
const cancelReservation = (id) => $axios({ url: `/api/dining/reservation/cancel/${id}`, method: 'put' })
const arriveReservation = (id) => $axios({ url: `/api/dining/reservation/arrive/${id}`, method: 'put' })
