const printerConfigPage = (params) => $axios({ url: '/printer/config/page', method: 'get', params })
const printerConfigList = (params) => $axios({ url: '/printer/config/list', method: 'get', params })
const addPrinterConfig = (params) => $axios({ url: '/printer/config', method: 'post', data: params })
const updatePrinterConfig = (params) => $axios({ url: '/printer/config', method: 'put', data: params })
const deletePrinterConfig = (id) => $axios({ url: `/printer/config/${id}`, method: 'delete' })
const getPrinterConfig = (id) => $axios({ url: `/printer/config/${id}`, method: 'get' })
const printerTest = (id) => $axios({ url: `/printer/test/${id}`, method: 'post' })
const printerStatus = (id) => $axios({ url: `/printer/status/${id}`, method: 'get' })
const printerPrint = (orderId, type) => $axios({ url: `/printer/print/${orderId}`, method: 'post', params: { type } })
const printerLogPage = (params) => $axios({ url: '/printer/log/page', method: 'get', params })
