const printerConfigPage = (params) => $axios({ url: '/printer/config/page', method: 'get', params })
// 修改点：打印机配置聚合统计（SQL 聚合，替代前端 pageSize:1000 拉全量）
const printerConfigStats = () => $axios({ url: '/printer/config/stats', method: 'get' })
const printerConfigList = (params) => $axios({ url: '/printer/config/list', method: 'get', params })
const addPrinterConfig = (params) => $axios({ url: '/printer/config', method: 'post', data: params })
const updatePrinterConfig = (params) => $axios({ url: '/printer/config', method: 'put', data: params })
const deletePrinterConfig = (id) => $axios({ url: `/printer/config/${id}`, method: 'delete' })
const getPrinterConfig = (id) => $axios({ url: `/printer/config/${id}`, method: 'get' })
const printerTest = (id) => $axios({ url: `/printer/test/${id}`, method: 'post' })
const printerStatus = (id) => $axios({ url: `/printer/status/${id}`, method: 'get' })
const printerPrint = (orderId, type) => $axios({ url: `/printer/print/${orderId}`, method: 'post', params: { type } })
const printerLogPage = (params) => $axios({ url: '/printer/log/page', method: 'get', params })
const printerConfigOptions = () => $axios({ url: '/printer/config/options', method: 'get' })
const listSystemPrinters = () => $axios({ url: '/printer/system/list', method: 'get' })
