const reportDaily = (params) => $axios({ url: '/api/report/daily', method: 'get', params })
const reportDishRanking = (params) => $axios({ url: '/api/report/dish-ranking', method: 'get', params })
const reportTimeSlot = (params) => $axios({ url: '/api/report/time-slot', method: 'get', params })
const reportPayment = (params) => $axios({ url: '/api/report/payment', method: 'get', params })
const reportCategorySales = (params) => $axios({ url: '/api/report/category-sales', method: 'get', params })
const reportDishTrend = (params) => $axios({ url: '/api/report/dish-trend', method: 'get', params })
const reportPaymentTrend = (params) => $axios({ url: '/api/report/payment/trend', method: 'get', params })
const reportTimeSlotHeatmap = (params) => $axios({ url: '/api/report/time-slot/heatmap', method: 'get', params })
const reportRepurchaseRate = (params) => $axios({ url: '/api/report/repurchase-rate', method: 'get', params })
const reportRepurchaseRateDish = (params) => $axios({ url: '/api/report/repurchase-rate/dish', method: 'get', params })
const reportCohort = (params) => $axios({ url: '/api/report/cohort', method: 'get', params })
const reportExportHistory = (params) => $axios({ url: '/api/report/export/history', method: 'get', params })
const deleteReportExportHistory = (id) => $axios({ url: `/api/report/export/history`, method: 'delete', params: { id } })
const reportExport = (params) => $axios({ url: '/api/report/export', method: 'get', params, responseType: 'blob' })
