-- Printer module test schema (H2 compatible)
-- Matches MyBatis-Plus 3.4.2 default UPPER_SNAKE_CASE column naming

DROP TABLE IF EXISTS PRINTER_LOG;
DROP TABLE IF EXISTS PRINTER_TEMPLATE;
DROP TABLE IF EXISTS PRINTER_CONFIG;

CREATE TABLE PRINTER_CONFIG (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    TENANT_ID BIGINT NULL DEFAULT NULL COMMENT '租户ID',
    STORE_ID BIGINT NULL DEFAULT NULL COMMENT '门店ID',
    NAME VARCHAR(100) NOT NULL COMMENT '打印机名称',
    TYPE VARCHAR(50) NOT NULL COMMENT '打印机类型',
    BRAND VARCHAR(50) NULL DEFAULT NULL COMMENT '打印机品牌',
    DEVICE_ID VARCHAR(100) NULL DEFAULT NULL COMMENT '设备ID',
    IP_ADDRESS VARCHAR(50) NULL DEFAULT NULL COMMENT 'IP地址',
    PORT INT NULL DEFAULT NULL COMMENT '端口号',
    PAPER_SIZE VARCHAR(20) NULL DEFAULT NULL COMMENT '纸张尺寸',
    PRINT_TYPES VARCHAR(100) NULL DEFAULT NULL COMMENT '打印类型（逗号分隔：BILL,KITCHEN,DELIVERY）',
    STATUS INT NULL DEFAULT NULL COMMENT '打印机状态：0-离线，1-在线',
    SORT INT NULL DEFAULT NULL COMMENT '排序号',
    CREATED_TIME DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    UPDATED_TIME DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    SYSTEM_PRINTER_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '系统打印机名称',
    PRIMARY KEY (ID)
);

CREATE TABLE PRINTER_LOG (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    TENANT_ID BIGINT NULL DEFAULT NULL COMMENT '租户ID',
    ORDER_ID BIGINT NOT NULL COMMENT '订单ID',
    PRINT_TYPE VARCHAR(50) NOT NULL COMMENT '打印类型（BILL,KITCHEN,DELIVERY）',
    PRINTER_ID BIGINT NOT NULL COMMENT '打印机ID',
    CONTENT TEXT NULL DEFAULT NULL COMMENT '打印内容',
    STATUS INT NULL DEFAULT NULL COMMENT '打印状态：0-失败，1-成功',
    ERROR_MSG VARCHAR(500) NULL DEFAULT NULL COMMENT '错误信息',
    CREATED_TIME DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (ID)
);

CREATE TABLE PRINTER_TEMPLATE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    NAME VARCHAR(100) NOT NULL COMMENT '模板名称',
    TYPE VARCHAR(50) NOT NULL COMMENT '模板类型',
    CONTENT TEXT NOT NULL COMMENT '模板内容',
    CREATED_TIME DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    UPDATED_TIME DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_PRINTER_CONFIG_TENANT_STORE ON PRINTER_CONFIG (TENANT_ID, STORE_ID);
CREATE INDEX IDX_PRINTER_CONFIG_STATUS ON PRINTER_CONFIG (STATUS);
CREATE INDEX IDX_PRINTER_LOG_TENANT ON PRINTER_LOG (TENANT_ID);
CREATE INDEX IDX_PRINTER_LOG_ORDER ON PRINTER_LOG (ORDER_ID);
CREATE INDEX IDX_PRINTER_LOG_PRINTER ON PRINTER_LOG (PRINTER_ID);
CREATE INDEX IDX_PRINTER_LOG_STATUS ON PRINTER_LOG (STATUS);
CREATE INDEX IDX_PRINTER_LOG_CREATED_TIME ON PRINTER_LOG (CREATED_TIME);
