-- Inventory module test schema (H2 compatible)
-- Matches MyBatis-Plus 3.4.2 default UPPER_SNAKE_CASE column naming

-- Drop child tables first, parent tables last

CREATE TABLE IF NOT EXISTS material_category (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  NAME varchar(50) NULL DEFAULT NULL COMMENT '分类名称',
  SORT int NULL DEFAULT NULL COMMENT '排序',
  CREATED_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS supplier (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  NAME varchar(100) NULL DEFAULT NULL COMMENT '供应商名称',
  CONTACT varchar(50) NULL DEFAULT NULL COMMENT '联系人',
  PHONE varchar(20) NULL DEFAULT NULL COMMENT 'ϵ绰',
  ADDRESS varchar(255) NULL DEFAULT NULL COMMENT '地址',
  LICENSE_IMAGES varchar(1000) NULL DEFAULT NULL COMMENT '资质图片（逗号分隔，最多5张）',
  STATUS int NULL DEFAULT NULL COMMENT '状态',
  CREATED_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS material (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  CATEGORY_ID bigint NULL DEFAULT NULL COMMENT '分类ID',
  NAME varchar(100) NULL DEFAULT NULL COMMENT '物料名称',
  UNIT varchar(20) NULL DEFAULT NULL COMMENT '单位',
  STOCK_QTY decimal(10,2) NULL DEFAULT NULL COMMENT '库存数量',
  MIN_STOCK decimal(10,2) NULL DEFAULT NULL COMMENT '最小库存',
  UNIT_PRICE decimal(10,2) NULL DEFAULT NULL COMMENT '单价',
  SUPPLIER_ID bigint NULL DEFAULT NULL COMMENT '供应商ID',
  BARCODE varchar(50) NULL DEFAULT NULL COMMENT '条形码',
  STATUS int NULL DEFAULT NULL COMMENT '状态（1-正常，0-禁用）',
  CREATED_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS purchase_order (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  ORDER_NO varchar(50) NULL DEFAULT NULL COMMENT '订单编号',
  SUPPLIER_ID bigint NULL DEFAULT NULL COMMENT '供应商ID',
  TOTAL_AMOUNT decimal(10,2) NULL DEFAULT NULL COMMENT '总金额',
  STATUS varchar(32) NULL DEFAULT NULL COMMENT '状态',
  OPERATOR varchar(50) NULL DEFAULT NULL COMMENT '操作员',
  REMARK varchar(200) NULL DEFAULT NULL COMMENT '备注',
  VOUCHER_IMAGES varchar(1000) NULL DEFAULT NULL COMMENT '凭证图片（逗号分隔，最多5张）',
  CREATED_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  VERSION int NOT NULL DEFAULT 0 COMMENT 'ֹ汾',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS stock_check (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  CHECK_NO varchar(50) NULL DEFAULT NULL COMMENT '盘点单号',
  STATUS varchar(32) NULL DEFAULT NULL COMMENT '状态',
  TOTAL_DIFF_AMOUNT decimal(10,2) NULL DEFAULT NULL COMMENT '总差异金额',
  OPERATOR varchar(50) NULL DEFAULT NULL COMMENT '操作员',
  REMARK varchar(200) NULL DEFAULT NULL COMMENT '备注',
  VOUCHER_IMAGES varchar(1000) NULL DEFAULT NULL COMMENT '凭证图片（逗号分隔，最多5张）',
  CREATED_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS purchase_order_detail (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  PURCHASE_ORDER_ID bigint NULL DEFAULT NULL COMMENT '采购订单ID',
  MATERIAL_ID bigint NULL DEFAULT NULL COMMENT '物料ID',
  QTY decimal(10,2) NULL DEFAULT NULL COMMENT '数量',
  UNIT_PRICE decimal(10,2) NULL DEFAULT NULL COMMENT '单价',
  AMOUNT decimal(10,2) NULL DEFAULT NULL COMMENT '金额',
  RECEIVED_QTY decimal(10,2) NULL DEFAULT NULL COMMENT '收货数量',
  REMARK varchar(200) NULL DEFAULT NULL COMMENT '备注',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS stock_check_detail (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  CHECK_ID bigint NULL DEFAULT NULL COMMENT '盘点ID',
  MATERIAL_ID bigint NULL DEFAULT NULL COMMENT '物料ID',
  BOOK_QTY decimal(10,2) NULL DEFAULT NULL COMMENT '账面数量',
  ACTUAL_QTY decimal(10,2) NULL DEFAULT NULL COMMENT '实际数量',
  DIFF_QTY decimal(10,2) NULL DEFAULT NULL COMMENT '差异数量',
  REMARK varchar(200) NULL DEFAULT NULL COMMENT '备注',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS dish_material (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  DISH_ID bigint NULL DEFAULT NULL COMMENT '菜品ID',
  MATERIAL_ID bigint NULL DEFAULT NULL COMMENT '食材ID',
  USAGE_QTY decimal(10,3) NULL DEFAULT NULL COMMENT '单份菜品消耗食材数量',
  SORT int NULL DEFAULT 0 COMMENT '排序',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS stock_record (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  MATERIAL_ID bigint NULL DEFAULT NULL COMMENT '物料ID',
  TYPE varchar(32) NULL DEFAULT NULL COMMENT '类型',
  QTY decimal(10,2) NULL DEFAULT NULL COMMENT '数量',
  UNIT_PRICE decimal(10,2) NULL DEFAULT NULL COMMENT '单价',
  TOTAL_AMOUNT decimal(10,2) NULL DEFAULT NULL COMMENT '总金额',
  BIZ_ID bigint NULL DEFAULT NULL COMMENT '业务ID',
  REMARK varchar(200) NULL DEFAULT NULL COMMENT '备注',
  VOUCHER_IMAGES varchar(1000) NULL DEFAULT NULL COMMENT '凭证图片（逗号分隔，最多5张）',
  OPERATOR varchar(50) NULL DEFAULT NULL COMMENT '操作员',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);

-- Separate CREATE INDEX statements for H2 compatibility

-- 价格历史记录表（H2 兼容）
CREATE TABLE IF NOT EXISTS price_history (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  MATERIAL_ID bigint NOT NULL COMMENT '物料ID',
  OLD_PRICE decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '旧价格',
  NEW_PRICE decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '新价格',
  CHANGE_REASON varchar(255) DEFAULT '' COMMENT '变动原因',
  OPERATOR_ID bigint NOT NULL DEFAULT 0 COMMENT '操作人ID',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
);

-- 供应商结算单表（H2 兼容）
CREATE TABLE IF NOT EXISTS supplier_settlement (
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  TENANT_ID bigint NULL DEFAULT NULL COMMENT '租户ID',
  SUPPLIER_ID bigint NOT NULL COMMENT '供应商ID',
  PERIOD varchar(20) NOT NULL COMMENT '结算周期',
  TOTAL_AMOUNT decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
  PAID_AMOUNT decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '已付金额',
  STATUS varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态',
  CREATE_TIME datetime NULL DEFAULT NULL COMMENT '创建时间',
  UPDATE_TIME datetime NULL DEFAULT NULL COMMENT '更新时间',
  CREATE_USER bigint NULL DEFAULT NULL COMMENT '创建人ID',
  UPDATE_USER bigint NULL DEFAULT NULL COMMENT '更新人ID',
  IS_DELETED int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (ID)
);
